"""
Unified Conversation Manager - Single source for conversation operations
Implements UUID-based message IDs and consistent conversation management
"""

import uuid
import datetime
import logging
import json
import os
from typing import Dict, List, Optional, Any
from contextlib import contextmanager
from app.database import get_db

logger = logging.getLogger(__name__)

@contextmanager
def get_db_context():
    """Context manager for database connections to ensure closure"""
    db = get_db()
    try:
        yield db
    finally:
        db.close()

def ensure_conversation_exists(conversation_id: Optional[str], user_id: int, title: Optional[str] = None) -> str:
    """
    Ensure conversation exists, create if missing
    Returns conversation_id (new or existing)
    
    IMPORTANT: This function should NOT generate new conversation IDs.
    Conversation IDs should only be generated by the sessions endpoint.
    If no conversation_id is provided, raise an error.
    """
    with get_db_context() as db:
        if not conversation_id:
            # CRITICAL: Frontend should always provide a conversation_id from backend
            # If missing, this is a frontend bug or missing session creation
            logger.error(f"❌ Missing conversation_id for user {user_id}. Frontend must create session first.")
            raise ValueError("Missing conversation_id. Create a session first using /api/sessions")
        
        logger.info(f"🔍 Checking existing conversation ID: {conversation_id} for user {user_id}")
        
        # Check if conversation exists
        conversation = db.execute(
            "SELECT id, title FROM conversations WHERE id = ? AND user_id = ?",
            (conversation_id, user_id)
        ).fetchone()
        
        if conversation:
            # Conversation exists, update title if provided
            if title and title != conversation[1]:
                db.execute(
                    "UPDATE conversations SET title = ?, updated_at = ? WHERE id = ?",
                    (title, datetime.datetime.now(), conversation_id)
                )
                db.commit()
                logger.info(f"📝 Updated conversation title: {conversation_id} -> {title}")
            else:
                logger.info(f"✅ Conversation already exists: {conversation_id} with title: {conversation[1]}")
            return conversation_id
        
        # Create new conversation
        if not title:
            title = f"Conversation {datetime.datetime.now().strftime('%Y-%m-%d %H:%M')}"
        
        db.execute(
            "INSERT INTO conversations (id, user_id, title, created_at, updated_at, message_count, total_tokens) VALUES (?, ?, ?, ?, ?, ?, ?)",
            (conversation_id, user_id, title, datetime.datetime.now(), datetime.datetime.now(), 0, 0)
        )
        db.commit()
        
        logger.info(f"✅ Created conversation {conversation_id} for user {user_id} with title: {title}")
        return conversation_id

def save_message(
    conversation_id: str, 
    user_id: int, 
    role: str, 
    content: str, 
    metadata: Optional[Dict] = None,
    model: Optional[str] = None,
    provider: Optional[str] = None
) -> Dict[str, Any]:
    """
    Save message to conversation with metadata using UUID for message ID
    Unified implementation used by all modules
    
    Args:
        conversation_id: Conversation ID
        user_id: User ID
        role: Message role (user/assistant/system)
        content: Message content
        metadata: Additional metadata (JSON)
        model: Model used for this message (default: 'gpt-3.5-turbo')
        provider: Provider used for this message (default: 'openai')
    """
    with get_db_context() as db:
        # Generate UUID for message
        message_id = str(uuid.uuid4())
        
        # Estimate tokens
        tokens = estimate_tokens(content)
        
        # Prepare metadata JSON - include provider/model if not already in metadata
        metadata_to_store = metadata or {}
        if model and "model" not in metadata_to_store:
            metadata_to_store["model"] = model
        if provider and "provider" not in metadata_to_store:
            metadata_to_store["provider"] = provider
            
        metadata_json = None
        if metadata_to_store:
            metadata_json = json.dumps(metadata_to_store)
        
        # Use provided model/provider or defaults
        model_to_store = model or "gpt-3.5-turbo"
        provider_to_store = provider or "openai"
        
        # Save message with UUID
        created_at = datetime.datetime.now()
        
        db.execute(
            "INSERT INTO messages (id, conversation_id, user_id, role, content, tokens, provider, model, metadata, created_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)",
            (message_id, conversation_id, user_id, role, content, tokens, provider_to_store, model_to_store, metadata_json, created_at)
        )
        
        # Update conversation
        db.execute(
            "UPDATE conversations SET message_count = message_count + 1, total_tokens = total_tokens + ?, updated_at = ? WHERE id = ?",
            (tokens, created_at, conversation_id)
        )
        
        db.commit()
        
        result = {
            "id": message_id,
            "conversation_id": conversation_id,
            "role": role,
            "content": content,
            "tokens": tokens,
            "model": model_to_store,
            "provider": provider_to_store,
            "metadata": metadata_to_store,
            "created_at": created_at
        }
        
        logger.info(f"✅ Saved message to conversation {conversation_id}, role: {role}, model: {model_to_store}, provider: {provider_to_store}, tokens: {tokens}")
        return result


def get_user_conversations(user_id: int, limit: Optional[int] = None, state: str = "active") -> List[Dict[str, Any]]:
    """
    Get all conversations for a user with optional state filter
    """
    with get_db_context() as db:
        query = """
            SELECT id, title, created_at, updated_at, message_count, total_tokens, state 
            FROM conversations 
            WHERE user_id = ? AND state = ?
            ORDER BY updated_at DESC
        """
        
        params = [user_id, state]
        
        if limit:
            query += " LIMIT ?"
            params.append(limit)
        
        conversations = db.execute(query, params).fetchall()
        
        result = []
        for conv in conversations:
            result.append({
                "id": conv[0],
                "title": conv[1],
                "created_at": conv[2],
                "updated_at": conv[3],
                "message_count": conv[4],
                "total_tokens": conv[5],
                "state": conv[6]
            })
        
        logger.info(f"✅ Retrieved {len(result)} conversations for user {user_id} (state: {state})")
        return result

def update_conversation_title(conversation_id: str, title: str):
    """
    Update conversation title
    """
    with get_db_context() as db:
        db.execute(
            "UPDATE conversations SET title = ?, updated_at = ? WHERE id = ?",
            (title, datetime.datetime.now(), conversation_id)
        )
        db.commit()
        
        logger.info(f"✅ Updated conversation title: {conversation_id} -> {title}")

def archive_conversation(conversation_id: str, user_id: int) -> bool:
    """
    Archive a conversation
    """
    try:
        with get_db_context() as db:
            result = db.execute(
                "UPDATE conversations SET state = 'archived', updated_at = ? WHERE id = ? AND user_id = ?",
                (datetime.datetime.now(), conversation_id, user_id)
            )
            db.commit()
            
            if result.rowcount > 0:
                logger.info(f"✅ Archived conversation: {conversation_id}")
                return True
            else:
                logger.warning(f"⚠️ Conversation {conversation_id} not found or doesn't belong to user {user_id}")
                return False
            
    except Exception as e:
        logger.error(f"❌ Failed to archive conversation {conversation_id}: {str(e)}")
        return False

def restore_conversation(conversation_id: str, user_id: int) -> bool:
    """
    Restore an archived conversation
    """
    try:
        with get_db_context() as db:
            result = db.execute(
                "UPDATE conversations SET state = 'active', updated_at = ? WHERE id = ? AND user_id = ?",
                (datetime.datetime.now(), conversation_id, user_id)
            )
            db.commit()
            
            if result.rowcount > 0:
                logger.info(f"✅ Restored conversation: {conversation_id}")
                return True
            else:
                logger.warning(f"⚠️ Conversation {conversation_id} not found or doesn't belong to user {user_id}")
                return False
            
    except Exception as e:
        logger.error(f"❌ Failed to restore conversation {conversation_id}: {str(e)}")
        return False

def delete_conversation(conversation_id: str, user_id: int) -> bool:
    """
    Delete conversation and associated data
    """
    try:
        with get_db_context() as db:
            # Verify conversation belongs to user
            conversation = db.execute(
                "SELECT id FROM conversations WHERE id = ? AND user_id = ?",
                (conversation_id, user_id)
            ).fetchone()
            
            if not conversation:
                logger.warning(f"⚠️ Conversation {conversation_id} not found or doesn't belong to user {user_id}")
                return False
            
            # Delete associated image files from disk
            images = db.execute(
                "SELECT file_path FROM media_library WHERE conversation_id = ? AND media_type = 'image'",
                (conversation_id,)
            ).fetchall()
            for row in images:
                fpath = row[0]
                if fpath and os.path.exists(fpath):
                    try:
                        os.remove(fpath)
                    except OSError:
                        pass

            # Delete messages
            db.execute("DELETE FROM messages WHERE conversation_id = ?", (conversation_id,))

            # Delete file references
            db.execute("DELETE FROM file_references WHERE conversation_id = ?", (conversation_id,))

            # Delete conversation
            db.execute("DELETE FROM conversations WHERE id = ?", (conversation_id,))
            
            db.commit()
            
            logger.info(f"✅ Deleted conversation: {conversation_id}")
            return True
        
    except Exception as e:
        logger.error(f"❌ Failed to delete conversation {conversation_id}: {str(e)}")
        return False

def get_conversation_stats(conversation_id: str) -> Dict[str, Any]:
    """
    Get conversation statistics
    """
    with get_db_context() as db:
        # Get conversation data
        conversation = db.execute(
            "SELECT message_count, total_tokens, created_at, updated_at, state FROM conversations WHERE id = ?",
            (conversation_id,)
        ).fetchone()
        
        if not conversation:
            return {
                "message_count": 0,
                "total_tokens": 0,
                "created_at": None,
                "updated_at": None,
                "state": None,
                "file_count": 0
            }
        
        # Get file count
        file_count = db.execute(
            "SELECT COUNT(*) FROM file_references WHERE conversation_id = ?",
            (conversation_id,)
        ).fetchone()[0]
        
        return {
            "message_count": conversation[0],
            "total_tokens": conversation[1],
            "created_at": conversation[2],
            "updated_at": conversation[3],
            "state": conversation[4],
            "file_count": file_count
        }

def estimate_tokens(text: str) -> int:
    """Accurate token estimation"""
    try:
        import tiktoken
        tokenizer = tiktoken.get_encoding("cl100k_base")
        return len(tokenizer.encode(text))
    except ImportError:
        # Fallback: rough estimation based on words
        return int(len(text.split()) * 1.3)

