"""
Unified Conversation Manager - Single source for conversation operations
Implements UUID-based message IDs and consistent conversation management
"""

import uuid
import datetime
import logging
import json
import os
import asyncio
from typing import Dict, List, Optional, Any
from contextlib import contextmanager
from functools import partial
from app.database import get_db
from app.core.prompts import SUMMARY_SYSTEM

logger = logging.getLogger(__name__)

@contextmanager
def get_db_context():
    """Context manager for database connections to ensure closure"""
    db = get_db()
    try:
        yield db
    finally:
        db.close()

def ensure_conversation_exists(conversation_id: Optional[str], user_id: int, title: Optional[str] = None) -> str:
    """
    Ensure conversation exists, create if missing
    Returns conversation_id (new or existing)
    
    IMPORTANT: This function should NOT generate new conversation IDs.
    Conversation IDs should only be generated by the sessions endpoint.
    If no conversation_id is provided, raise an error.
    """
    with get_db_context() as db:
        if not conversation_id:
            # CRITICAL: Frontend should always provide a conversation_id from backend
            # If missing, this is a frontend bug or missing session creation
            logger.error(f"❌ Missing conversation_id for user {user_id}. Frontend must create session first.")
            raise ValueError("Missing conversation_id. Create a session first using /api/sessions")
        
        logger.info(f"🔍 Checking existing conversation ID: {conversation_id} for user {user_id}")
        
        # Check if conversation exists
        conversation = db.execute(
            "SELECT id, title FROM conversations WHERE id = ? AND user_id = ?",
            (conversation_id, user_id)
        ).fetchone()
        
        if conversation:
            # Conversation exists, update title if provided
            if title and title != conversation[1]:
                db.execute(
                    "UPDATE conversations SET title = ?, updated_at = ? WHERE id = ?",
                    (title, datetime.datetime.now(), conversation_id)
                )
                db.commit()
                logger.info(f"📝 Updated conversation title: {conversation_id} -> {title}")
            else:
                logger.info(f"✅ Conversation already exists: {conversation_id} with title: {conversation[1]}")
            return conversation_id
        
        # Create new conversation
        if not title:
            title = f"Conversation {datetime.datetime.now().strftime('%Y-%m-%d %H:%M')}"
        
        db.execute(
            "INSERT INTO conversations (id, user_id, title, created_at, updated_at, message_count, total_tokens) VALUES (?, ?, ?, ?, ?, ?, ?)",
            (conversation_id, user_id, title, datetime.datetime.now(), datetime.datetime.now(), 0, 0)
        )
        db.commit()
        
        logger.info(f"✅ Created conversation {conversation_id} for user {user_id} with title: {title}")
        return conversation_id

def save_message(
    conversation_id: str, 
    user_id: int, 
    role: str, 
    content: str, 
    metadata: Optional[Dict] = None,
    model: Optional[str] = None,
    provider: Optional[str] = None
) -> Dict[str, Any]:
    """
    Save message to conversation with metadata using UUID for message ID
    Unified implementation used by all modules
    
    Args:
        conversation_id: Conversation ID
        user_id: User ID
        role: Message role (user/assistant/system)
        content: Message content
        metadata: Additional metadata (JSON)
        model: Model used for this message (default: 'gpt-3.5-turbo')
        provider: Provider used for this message (default: 'openai')
    """
    with get_db_context() as db:
        # Generate UUID for message
        message_id = str(uuid.uuid4())
        
        # Estimate tokens
        tokens = estimate_tokens(content)
        
        # Prepare metadata JSON - include provider/model if not already in metadata
        metadata_to_store = metadata or {}
        if model and "model" not in metadata_to_store:
            metadata_to_store["model"] = model
        if provider and "provider" not in metadata_to_store:
            metadata_to_store["provider"] = provider
            
        metadata_json = None
        if metadata_to_store:
            metadata_json = json.dumps(metadata_to_store)
        
        # Use provided model/provider or defaults
        model_to_store = model or "gpt-3.5-turbo"
        provider_to_store = provider or "openai"
        
        # Save message with UUID
        created_at = datetime.datetime.now()
        
        db.execute(
            "INSERT INTO messages (id, conversation_id, user_id, role, content, tokens, provider, model, metadata, created_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)",
            (message_id, conversation_id, user_id, role, content, tokens, provider_to_store, model_to_store, metadata_json, created_at)
        )
        
        # Update conversation
        db.execute(
            "UPDATE conversations SET message_count = message_count + 1, total_tokens = total_tokens + ?, updated_at = ? WHERE id = ?",
            (tokens, created_at, conversation_id)
        )
        
        db.commit()
        
        result = {
            "id": message_id,
            "conversation_id": conversation_id,
            "role": role,
            "content": content,
            "tokens": tokens,
            "model": model_to_store,
            "provider": provider_to_store,
            "metadata": metadata_to_store,
            "created_at": created_at
        }
        
        logger.info(f"✅ Saved message to conversation {conversation_id}, role: {role}, model: {model_to_store}, provider: {provider_to_store}, tokens: {tokens}")
        return result


def get_conversation_messages(conversation_id: str, limit: Optional[int] = None) -> List[Dict[str, Any]]:
    """
    Get messages for a conversation
    """
    with get_db_context() as db:
        query = """
            SELECT id, role, content, tokens, metadata, created_at 
            FROM messages 
            WHERE conversation_id = ? 
            ORDER BY created_at ASC
        """
        
        if limit:
            query += " LIMIT ?"
            messages = db.execute(query, (conversation_id, limit)).fetchall()
        else:
            messages = db.execute(query, (conversation_id,)).fetchall()
        
        result = []
        for msg in messages:
            message_data = {
                "id": msg[0],
                "role": msg[1],
                "content": msg[2],
                "tokens": msg[3],
                "created_at": msg[5]
            }
            
            # Parse metadata if available
            if msg[4]:
                try:
                    metadata = json.loads(msg[4])
                    message_data["metadata"] = metadata
                except:
                    message_data["metadata"] = {}
            else:
                message_data["metadata"] = {}
            
            result.append(message_data)
        
        logger.info(f"✅ Retrieved {len(result)} messages for conversation {conversation_id}")
        return result

def get_last_n_messages(conversation_id: str, n: int = 10) -> List[Dict[str, Any]]:
    """
    Get last N messages from conversation (UI history)
    """
    with get_db_context() as db:
        messages = db.execute(
            "SELECT role, content, created_at FROM messages WHERE conversation_id = ? ORDER BY created_at DESC LIMIT ?",
            (conversation_id, n)
        ).fetchall()
        
        # Return in chronological order
        return [
            {"role": msg[0], "content": msg[1], "created_at": msg[2]}
            for msg in reversed(messages)
        ]

def get_user_conversations(user_id: int, limit: Optional[int] = None, state: str = "active") -> List[Dict[str, Any]]:
    """
    Get all conversations for a user with optional state filter
    """
    with get_db_context() as db:
        query = """
            SELECT id, title, created_at, updated_at, message_count, total_tokens, state 
            FROM conversations 
            WHERE user_id = ? AND state = ?
            ORDER BY updated_at DESC
        """
        
        params = [user_id, state]
        
        if limit:
            query += " LIMIT ?"
            params.append(limit)
        
        conversations = db.execute(query, params).fetchall()
        
        result = []
        for conv in conversations:
            result.append({
                "id": conv[0],
                "title": conv[1],
                "created_at": conv[2],
                "updated_at": conv[3],
                "message_count": conv[4],
                "total_tokens": conv[5],
                "state": conv[6]
            })
        
        logger.info(f"✅ Retrieved {len(result)} conversations for user {user_id} (state: {state})")
        return result

def update_conversation_title(conversation_id: str, title: str):
    """
    Update conversation title
    """
    with get_db_context() as db:
        db.execute(
            "UPDATE conversations SET title = ?, updated_at = ? WHERE id = ?",
            (title, datetime.datetime.now(), conversation_id)
        )
        db.commit()
        
        logger.info(f"✅ Updated conversation title: {conversation_id} -> {title}")

def archive_conversation(conversation_id: str, user_id: int) -> bool:
    """
    Archive a conversation
    """
    try:
        with get_db_context() as db:
            result = db.execute(
                "UPDATE conversations SET state = 'archived', updated_at = ? WHERE id = ? AND user_id = ?",
                (datetime.datetime.now(), conversation_id, user_id)
            )
            db.commit()
            
            if result.rowcount > 0:
                logger.info(f"✅ Archived conversation: {conversation_id}")
                return True
            else:
                logger.warning(f"⚠️ Conversation {conversation_id} not found or doesn't belong to user {user_id}")
                return False
            
    except Exception as e:
        logger.error(f"❌ Failed to archive conversation {conversation_id}: {str(e)}")
        return False

def restore_conversation(conversation_id: str, user_id: int) -> bool:
    """
    Restore an archived conversation
    """
    try:
        with get_db_context() as db:
            result = db.execute(
                "UPDATE conversations SET state = 'active', updated_at = ? WHERE id = ? AND user_id = ?",
                (datetime.datetime.now(), conversation_id, user_id)
            )
            db.commit()
            
            if result.rowcount > 0:
                logger.info(f"✅ Restored conversation: {conversation_id}")
                return True
            else:
                logger.warning(f"⚠️ Conversation {conversation_id} not found or doesn't belong to user {user_id}")
                return False
            
    except Exception as e:
        logger.error(f"❌ Failed to restore conversation {conversation_id}: {str(e)}")
        return False

def delete_conversation(conversation_id: str, user_id: int) -> bool:
    """
    Delete conversation and associated data
    """
    try:
        with get_db_context() as db:
            # Verify conversation belongs to user
            conversation = db.execute(
                "SELECT id FROM conversations WHERE id = ? AND user_id = ?",
                (conversation_id, user_id)
            ).fetchone()
            
            if not conversation:
                logger.warning(f"⚠️ Conversation {conversation_id} not found or doesn't belong to user {user_id}")
                return False
            
            # Delete associated image files from disk
            images = db.execute(
                "SELECT file_path FROM media_library WHERE conversation_id = ? AND media_type = 'image'",
                (conversation_id,)
            ).fetchall()
            for row in images:
                fpath = row[0]
                if fpath and os.path.exists(fpath):
                    try:
                        os.remove(fpath)
                    except OSError:
                        pass

            # Delete messages
            db.execute("DELETE FROM messages WHERE conversation_id = ?", (conversation_id,))

            # Delete file references
            db.execute("DELETE FROM file_references WHERE conversation_id = ?", (conversation_id,))

            # Delete conversation
            db.execute("DELETE FROM conversations WHERE id = ?", (conversation_id,))
            
            db.commit()
            
            logger.info(f"✅ Deleted conversation: {conversation_id}")
            return True
        
    except Exception as e:
        logger.error(f"❌ Failed to delete conversation {conversation_id}: {str(e)}")
        return False

def get_conversation_stats(conversation_id: str) -> Dict[str, Any]:
    """
    Get conversation statistics
    """
    with get_db_context() as db:
        # Get conversation data
        conversation = db.execute(
            "SELECT message_count, total_tokens, created_at, updated_at, state FROM conversations WHERE id = ?",
            (conversation_id,)
        ).fetchone()
        
        if not conversation:
            return {
                "message_count": 0,
                "total_tokens": 0,
                "created_at": None,
                "updated_at": None,
                "state": None,
                "file_count": 0
            }
        
        # Get file count
        file_count = db.execute(
            "SELECT COUNT(*) FROM file_references WHERE conversation_id = ?",
            (conversation_id,)
        ).fetchone()[0]
        
        return {
            "message_count": conversation[0],
            "total_tokens": conversation[1],
            "created_at": conversation[2],
            "updated_at": conversation[3],
            "state": conversation[4],
            "file_count": file_count
        }

def estimate_tokens(text: str) -> int:
    """Accurate token estimation"""
    try:
        import tiktoken
        tokenizer = tiktoken.get_encoding("cl100k_base")
        return len(tokenizer.encode(text))
    except ImportError:
        # Fallback: rough estimation based on words
        return int(len(text.split()) * 1.3)

def get_conversation_summary(conversation_id: str) -> Optional[str]:
    """
    Get conversation summary from conversation_summaries table
    """
    with get_db_context() as db:
        result = db.execute(
            "SELECT summary FROM conversation_summaries WHERE conversation_id = ?",
            (conversation_id,)
        ).fetchone()
        
        return result[0] if result else None

def save_conversation_summary(conversation_id: str, summary: str) -> bool:
    """
    Save or update conversation summary
    """
    try:
        with get_db_context() as db:
            db.execute(
                "INSERT OR REPLACE INTO conversation_summaries (conversation_id, summary, updated_at) VALUES (?, ?, ?)",
                (conversation_id, summary, datetime.datetime.now())
            )
            db.commit()
            logger.info(f"✅ Saved summary for conversation {conversation_id}")
            return True
    except Exception as e:
        logger.error(f"❌ Failed to save summary for conversation {conversation_id}: {str(e)}")
        return False

def should_summarize_conversation(conversation_id: str, threshold: int = 2000) -> bool:
    """
    Check if conversation should be summarized based on UN-SUMMARIZED token count.
    Threshold default is 2000 tokens (approx 1500 words).
    """
    try:
        with get_db_context() as db:
            # Get last summary time
            summary = db.execute(
                "SELECT updated_at FROM conversation_summaries WHERE conversation_id = ?",
                (conversation_id,)
            ).fetchone()
            
            last_summary_time = summary[0] if summary else None
            
            # Count tokens of messages since last summary
            if last_summary_time:
                result = db.execute(
                    "SELECT SUM(tokens) FROM messages WHERE conversation_id = ? AND created_at > ?",
                    (conversation_id, last_summary_time)
                ).fetchone()
            else:
                result = db.execute(
                    "SELECT SUM(tokens) FROM messages WHERE conversation_id = ?",
                    (conversation_id,)
                ).fetchone()
                
            token_count = result[0] if result and result[0] else 0
            
            # Also summarize if it's the first time and we have > 500 tokens (approx 10 messages)
            # to avoid waiting too long for the first summary
            if not last_summary_time and token_count > 500:
                return True
                
            return token_count > threshold
    except Exception as e:
        logger.error(f"❌ Failed to check summarization for conversation {conversation_id}: {str(e)}")
        return False

def get_recent_messages_for_summarization(conversation_id: str, limit: int = 20) -> List[Dict[str, Any]]:
    """
    Get recent messages for summarization.
    Kept for backward compatibility, but delegates to get_unsummarized_messages if appropriate?
    No, just keep it as utility.
    """
    try:
        with get_db_context() as db:
            messages = db.execute(
                "SELECT role, content FROM messages WHERE conversation_id = ? ORDER BY created_at DESC LIMIT ?",
                (conversation_id, limit)
            ).fetchall()
            
            # Return in chronological order
            return [
                {"role": msg[0], "content": msg[1]}
                for msg in reversed(messages)
            ]
    except Exception as e:
        logger.error(f"❌ Failed to get messages for summarization: {str(e)}")
        return []

def get_unsummarized_messages(conversation_id: str) -> List[Dict[str, Any]]:
    """Get messages that haven't been summarized yet"""
    try:
        with get_db_context() as db:
            # Get last summary time
            summary = db.execute(
                "SELECT updated_at FROM conversation_summaries WHERE conversation_id = ?",
                (conversation_id,)
            ).fetchone()
            
            last_summary_time = summary[0] if summary else None
            
            if last_summary_time:
                messages = db.execute(
                    "SELECT role, content FROM messages WHERE conversation_id = ? AND created_at > ? ORDER BY created_at ASC",
                    (conversation_id, last_summary_time)
                ).fetchall()
            else:
                messages = db.execute(
                    "SELECT role, content FROM messages WHERE conversation_id = ? ORDER BY created_at ASC",
                    (conversation_id,)
                ).fetchall()
                
            return [{"role": msg[0], "content": msg[1]} for msg in messages]
    except Exception as e:
        logger.error(f"❌ Failed to get unsummarized messages: {str(e)}")
        return []


# ── Summarization via local GGUF model ──────────────────────────────

# ponytail: small local model path for summarization; swap if you want a larger one
SUMMARY_MODEL_PATH = os.path.abspath(os.path.join(os.path.dirname(__file__), "../../models/Qwen3-0.6B-Q6_K.gguf"))


def delete_conversation_summary(conversation_id: str) -> bool:
    """Delete conversation summary."""
    try:
        db = get_db()
        db.execute(
            "DELETE FROM conversation_summaries WHERE conversation_id = ?",
            (conversation_id,)
        )
        db.commit()
        logger.info(f"Deleted summary for conversation {conversation_id}")
        return True
    except Exception as e:
        logger.error(f"Failed to delete summary for conversation {conversation_id}: {e}")
        return False


async def generate_conversation_summary_llm(conversation_id: str, messages: List[Dict[str, Any]], user_id: int) -> Optional[str]:
    """
    Generate or update conversation summary using a local GGUF model.
    Uses the cached SUMMARY_MODEL_PATH; falls back silently on failure.
    """
    if not messages:
        return None

    try:
        old_summary = get_conversation_summary(conversation_id)

        new_conversation_text = ""
        for msg in messages:
            speaker = "User" if msg["role"] == "user" else "Assistant"
            new_conversation_text += f"{speaker}: {msg['content']}\n\n"

        if os.path.exists(SUMMARY_MODEL_PATH):
            try:
                def run_gguf_summary(prompt_text, m_path):
                    try:
                        from llama_cpp import Llama
                        from app.hardware.detection import get_llamacpp_settings

                        settings = get_llamacpp_settings()
                        llm = Llama(
                            model_path=m_path,
                            n_ctx=4096,
                            n_threads=settings["n_threads"],
                            n_gpu_layers=settings["n_gpu_layers"],
                            verbose=False,
                            use_mmap=settings.get("use_mmap", True),
                            use_mlock=settings.get("use_mlock", False)
                        )
                        output = llm(
                            prompt_text,
                            max_tokens=300,
                            stop=["<|im_end|>", "User:", "System:"],
                            temperature=0.3,
                            echo=False
                        )
                        return output["choices"][0]["text"].strip()
                    except Exception as e:
                        logger.error(f"GGUF inference internal error: {e}")
                        return None

                prompt = f"""Update the conversation summary with new events.

                Current Summary:
                {old_summary if old_summary else "No previous summary."}

                New Messages:
                {new_conversation_text}

                Instructions:
                1. Update the Current Summary to include key events from New Messages.
                2. Maintain a coherent narrative flow.
                3. Focus on actions, decisions, and current topic status.

                Updated Summary:"""

                formatted_prompt = f"<|start_header_id|>system<|end_header_id|>\n\n{SUMMARY_SYSTEM}<|eot_id|><|start_header_id|>user<|end_header_id|>\n\n{prompt}<|eot_id|><|start_header_id|>assistant<|end_header_id|>\n\n"

                loop = asyncio.get_running_loop()
                summary = await loop.run_in_executor(None, partial(run_gguf_summary, formatted_prompt, SUMMARY_MODEL_PATH))

                if summary:
                    logger.info(f"Generated Rolling Summary for {conversation_id}")
                    return summary

            except Exception as gguf_error:
                logger.error(f"GGUF summarization failed: {gguf_error}")

        logger.warning("GGUF summary failed, returning None to retry later.")
        return None

    except Exception as e:
        logger.error(f"Failed to generate summary: {e}")
        return None
