[package]
name = "lm-webui-desktop"
version = "0.8.3"
description = "LM-WebUI desktop application"
authors = ["LM-WebUI"]
edition = "2021"

[lib]
name = "lm_webui_desktop_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
portpicker = "0.1"
ureq = "3"

[features]
custom-protocol = ["tauri/custom-protocol"]
